version: '3.3'

services:
  db:
    restart: unless-stopped
    image: postgres:11.4-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: mydatabase
    volumes:
      - ./data:/var/lib/postgresql/data
